<template>
  <v-footer>
    <v-col 
      class="text-center"
      cols="12">
      <v-btn
        href="#"
        text
      >
        <v-icon>mdi-github</v-icon>
      </v-btn>
    </v-col>
  </v-footer>
</template>